### ISSUE TITLE
Siege weapons

### ISSUE THREAD

**Issue by jaker1** [CosmicDan-Minecraft/AncientWarfare2_CosmicDanFork#10]
Why there is no any siege weapons in 1.7.10?
 I met them in 1.6.4.

**Comment by cosmicdan** [comment]
Because they need a lot of work to be ported (converted) to Minecraft 1.7.10. Shadowmage (the creator of AW2) never found the time to finish it before he left us. I have looked at it, to try and do this - but it's a lot of work.

**Comment by jaker1** [comment]
So it will never be added ???

**Comment by cosmicdan** [comment]
I don't know? I don't control what happens with the mod, it's open source and I am just a contributor. Anybody can contribute.

On 15 Sep 2016, jaker1 notifications@github.com wrote:

> So it will never be added ???

## 

Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by jaker1** [comment]
Ok thank you

**Comment by jaker1** [comment]
Hello!
Are tou working on this subject still.
If yes, what is going on?

**Comment by cosmicdan** [comment]
No. I said I am not working on it and have no plans to.

**Comment by jaker1** [comment]
No i mean on AW

**Comment by jaker1** [comment]
Not on vehicles

**Comment by cosmicdan** [comment]
Of course, you can see my progress in the commit log.

Most of my recent changes are specific for the Reign Modpack, I don't think the current code will even work without some of my other code from other mods I made for the pack. Don't know. I'm not really interested in releasing or supporting the base AW2 anymore, only this modpack (which AW2 is the centerpiece of).

**Comment by cosmicdan** [comment]
No longer being developed by me.
