### ISSUE TITLE
Command in aw2

### ISSUE THREAD

**Issue by jaker1** [CosmicDan-Minecraft/AncientWarfare2_CosmicDanFork#14]
Sorry but one question about Ancient Warfare 2 in minecraft 1.7.10.How to choose command or flag as it was in 1.6.4.
I want to fight with my friend's army, but I have no idea of how to do this.

**Comment by cosmicdan** [comment]
I don't know what you mean.

Do you mean the Command Baton? To order soldiers? You craft the baton, and i think you use the Z/X/C keys to do stuff. That's the only type of commanding that I know, but I haven't played that part for a long time so I'm not sure...

**Comment by cosmicdan** [comment]
If you want to fight WITH your friend (not against), also make sure you are on the same team. Use /scoreboard command to make a team and join, it's a vanilla command. Can check for instructions in Google here.

**Comment by jaker1** [comment]
I mean to create 2 teams and fight with each other.
I and my friend should be enemies.

**Comment by cosmicdan** [comment]
Use the command baton.

Please read the instruction manual before asking more questions - https://github.com/HostileNetworks/AncientWarfare2_ReignModpack/blob/2.5_work/releases/dev/instruction_manual_2.3.75-beta.pdf

Even so, you will be better off asking for general support from the MCF thread. I don't actually play this part of the mod, other players are more experienced than I.

**Comment by jaker1** [comment]
Thanks, you really helped a lot with link that you gave me!
