### ISSUE TITLE
Farmers picking up dropped weapon - becoming soldiers

### ISSUE THREAD

**Issue by Dulciphi** [CosmicDan-Minecraft/AncientWarfare2_CosmicDanFork#4]
(This may have been fixed in Master. Need to check).

When a worker of any kind encounters a dropped tool/weapon of any kind, they pick it up, dropping their previous tool. This of course changes their role. 

To make matters worse, there is no check to see if the dropped weapon/tool is better than the one they were holding previously. No check for damage stats or durability. 

This results in endless weapon/tool swapping

**Comment by cosmicdan** [comment]
Does this still happen?

**Comment by cosmicdan** [comment]
Closing, we'll sort it if we find it again.
