### ISSUE TITLE
Add more tooltips and help texts

### ISSUE THREAD

**Issue by cosmicdan** [CosmicDan-Minecraft/AncientWarfare2_CosmicDanFork#6]
I made a recent update that allows "automatic assignment" of tooltips to GUI Buttons, Checkboxes, Labels and Tabs. Existing "manual" tooltips for these controls will be moved over.

More things need tooltips as they're confusing to new players, e.g. the routing order slip. I have already created a couple examples of new tooltip format, which requires only the addition of strings to the lang file. See here - https://github.com/cosmicdan/AncientWarfare2/commit/75fdfbef649f5e36e3de4a85ae3c6a64a4992521#diff-8394e8da0932defe4b7fe06681a43b58

"guistrings.inventory.direction.*.tooltip" is a wildcard tooltip which will apply to all applicable controls starting with guistrings.inventory.direction. - in this case the one tooltip is assigned to all of the direction buttons just above it. You can batch-assign tooltips using the \* (wildcard) character on the LAST segment (the text after the last .) only.

"guistrings.npc.repack.tooltip" is the basic tooltip addition. Add .tooltip to the end of an existing control to assign a tooltip to it. This will also override any wildcard tooltip that would have applied, since it's more specific (e.g. guistrings.inventory.direction.east.tooltip would take priority for the East tooltip).

"guistrings.npc.tool_slot" is not part of the new automatic-assignment, but illustrates use of \n to insert a newline character if you wish to manually do new lines in the tooltip.

Note that, with or without the presence of \n newline characters, all lines in the tooltip will wrap after a maximum of 40 characters.

Finally, I am almost certain that some strings are used on multiple GUI's, and adding one tooltip to them would only make sense in the context of one GUI but not another one which uses the same button text. I will need to split these in code, but I can do this as I update them.

**Comment by cosmicdan** [comment]
Example screenshot for the mentioned guistrings.inventory.direction.*.tooltip entry:

![tooltip_example](https://cloud.githubusercontent.com/assets/2092676/16846078/6c7eeb6e-4a2e-11e6-8b3a-1e6095881572.png)

**Comment by jaker1** [comment]
Great!!!
Is something that's really needed to add.

**Comment by cosmicdan** [comment]
No longer being developed by me.
